---
- name: Validate nginx config
  ansible.builtin.command: nginx -t
  changed_when: false
  listen: reload nginx

- name: Actually reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: reloaded
  listen: reload nginx
