apiVersion: v1
kind: ConfigMap
metadata:
  name: contoso-config
  namespace: contoso
data:
  DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/contoso
  S3_ENDPOINT_URL: http://minio:9000
  S3_PUBLIC_URL_BASE: http://localhost:9000/contoso-images
  S3_BUCKET: contoso-images
  S3_REGION: us-east-1